# TCL File Generated by Component Editor 15.1
# Tue Dec 13 15:06:36 CET 2016
# DO NOT MODIFY


# 
# Display_Segment "7Segment" v1.0
# FD 2016.12.13.15:06:36
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Display_Segment
# 
set_module_property DESCRIPTION ""
set_module_property NAME Display_Segment
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Display extension board"
set_module_property AUTHOR FD
set_module_property DISPLAY_NAME 7Segment
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RTC_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Display_7Segment.vhd VHDL PATH ../hdl/Display_7Segment.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point mm_params
# 
add_interface mm_params avalon end
set_interface_property mm_params addressUnits WORDS
set_interface_property mm_params associatedClock clock
set_interface_property mm_params associatedReset reset_sink
set_interface_property mm_params bitsPerSymbol 8
set_interface_property mm_params burstOnBurstBoundariesOnly false
set_interface_property mm_params burstcountUnits WORDS
set_interface_property mm_params explicitAddressSpan 0
set_interface_property mm_params holdTime 0
set_interface_property mm_params linewrapBursts false
set_interface_property mm_params maximumPendingReadTransactions 0
set_interface_property mm_params maximumPendingWriteTransactions 0
set_interface_property mm_params readLatency 0
set_interface_property mm_params readWaitTime 1
set_interface_property mm_params setupTime 0
set_interface_property mm_params timingUnits Cycles
set_interface_property mm_params writeWaitTime 0
set_interface_property mm_params ENABLED true
set_interface_property mm_params EXPORT_OF ""
set_interface_property mm_params PORT_NAME_MAP ""
set_interface_property mm_params CMSIS_SVD_VARIABLES ""
set_interface_property mm_params SVD_ADDRESS_GROUP ""

add_interface_port mm_params mm_params_address address Input 3
add_interface_port mm_params mm_params_read read Input 1
add_interface_port mm_params mm_params_readdata readdata Output 32
add_interface_port mm_params mm_params_write write Input 1
add_interface_port mm_params mm_params_writedata writedata Input 32
set_interface_assignment mm_params embeddedsw.configuration.isFlash 0
set_interface_assignment mm_params embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_params embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_params embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point Reset_Led
# 
add_interface Reset_Led conduit end
set_interface_property Reset_Led associatedClock clock
set_interface_property Reset_Led associatedReset ""
set_interface_property Reset_Led ENABLED true
set_interface_property Reset_Led EXPORT_OF ""
set_interface_property Reset_Led PORT_NAME_MAP ""
set_interface_property Reset_Led CMSIS_SVD_VARIABLES ""
set_interface_property Reset_Led SVD_ADDRESS_GROUP ""

add_interface_port Reset_Led Reset_Led writeresponsevalid_n Output 1


# 
# connection point SelSeg
# 
add_interface SelSeg conduit end
set_interface_property SelSeg associatedClock clock
set_interface_property SelSeg associatedReset ""
set_interface_property SelSeg ENABLED true
set_interface_property SelSeg EXPORT_OF ""
set_interface_property SelSeg PORT_NAME_MAP ""
set_interface_property SelSeg CMSIS_SVD_VARIABLES ""
set_interface_property SelSeg SVD_ADDRESS_GROUP ""

add_interface_port SelSeg SelSeg readdata Output 8


# 
# connection point nSelDig
# 
add_interface nSelDig conduit end
set_interface_property nSelDig associatedClock clock
set_interface_property nSelDig associatedReset ""
set_interface_property nSelDig ENABLED true
set_interface_property nSelDig EXPORT_OF ""
set_interface_property nSelDig PORT_NAME_MAP ""
set_interface_property nSelDig CMSIS_SVD_VARIABLES ""
set_interface_property nSelDig SVD_ADDRESS_GROUP ""

add_interface_port nSelDig nSelDig readdata Output 6

