# TCL File Generated by Component Editor 15.1
# Tue Dec 13 18:10:45 CET 2016
# DO NOT MODIFY


# 
# Display_Segment "7Segment" v1.2
# FD 2016.12.13.18:10:45
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Display_Segment
# 
set_module_property DESCRIPTION ""
set_module_property NAME Display_Segment
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Display extension board"
set_module_property AUTHOR FD
set_module_property DISPLAY_NAME 7Segment
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RTC_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Display_7Segment.vhd VHDL PATH ../hdl/Display_7Segment.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point Reset_Led
# 
add_interface Reset_Led conduit end
set_interface_property Reset_Led associatedClock clock
set_interface_property Reset_Led associatedReset ""
set_interface_property Reset_Led ENABLED true
set_interface_property Reset_Led EXPORT_OF ""
set_interface_property Reset_Led PORT_NAME_MAP ""
set_interface_property Reset_Led CMSIS_SVD_VARIABLES ""
set_interface_property Reset_Led SVD_ADDRESS_GROUP ""

add_interface_port Reset_Led Reset_Led writeresponsevalid_n Output 1


# 
# connection point SelSeg
# 
add_interface SelSeg conduit end
set_interface_property SelSeg associatedClock clock
set_interface_property SelSeg associatedReset ""
set_interface_property SelSeg ENABLED true
set_interface_property SelSeg EXPORT_OF ""
set_interface_property SelSeg PORT_NAME_MAP ""
set_interface_property SelSeg CMSIS_SVD_VARIABLES ""
set_interface_property SelSeg SVD_ADDRESS_GROUP ""

add_interface_port SelSeg SelSeg readdata Output 8


# 
# connection point nSelDig
# 
add_interface nSelDig conduit end
set_interface_property nSelDig associatedClock clock
set_interface_property nSelDig associatedReset ""
set_interface_property nSelDig ENABLED true
set_interface_property nSelDig EXPORT_OF ""
set_interface_property nSelDig PORT_NAME_MAP ""
set_interface_property nSelDig CMSIS_SVD_VARIABLES ""
set_interface_property nSelDig SVD_ADDRESS_GROUP ""

add_interface_port nSelDig nSelDig readdata Output 6


# 
# connection point mm_slave
# 
add_interface mm_slave avalon end
set_interface_property mm_slave addressUnits WORDS
set_interface_property mm_slave associatedClock clock
set_interface_property mm_slave associatedReset reset_sink
set_interface_property mm_slave bitsPerSymbol 8
set_interface_property mm_slave burstOnBurstBoundariesOnly false
set_interface_property mm_slave burstcountUnits WORDS
set_interface_property mm_slave explicitAddressSpan 0
set_interface_property mm_slave holdTime 0
set_interface_property mm_slave linewrapBursts false
set_interface_property mm_slave maximumPendingReadTransactions 0
set_interface_property mm_slave maximumPendingWriteTransactions 0
set_interface_property mm_slave readLatency 0
set_interface_property mm_slave readWaitTime 1
set_interface_property mm_slave setupTime 0
set_interface_property mm_slave timingUnits Cycles
set_interface_property mm_slave writeWaitTime 0
set_interface_property mm_slave ENABLED true
set_interface_property mm_slave EXPORT_OF ""
set_interface_property mm_slave PORT_NAME_MAP ""
set_interface_property mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave SVD_ADDRESS_GROUP ""

add_interface_port mm_slave mm_slave_address address Input 1
add_interface_port mm_slave mm_slave_read read Input 1
add_interface_port mm_slave mm_slave_readdata readdata Output 32
add_interface_port mm_slave mm_slave_write write Input 1
add_interface_port mm_slave mm_slave_writedata writedata Input 32
set_interface_assignment mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave embeddedsw.configuration.isPrintableDevice 0

